# Generated by Django 4.2.5 on 2023-09-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='form_images/')),
                ('image2', models.ImageField(upload_to='form_images/')),
                ('image3', models.ImageField(upload_to='form_images/')),
                ('name', models.CharField(max_length=19)),
            ],
        ),
    ]
