# Generated by Django 4.2.5 on 2023-09-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='form_images/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='form_images/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='form_images/'),
        ),
    ]
